full model replacement
lunar-sway/minestuck pull request #560
Opened 2024-02-03 19:20 UTC by KingBalDoro

a simple PR that seeks to update the prismarine armor's model and texture. future changes to the armor's model and texture are likely.

2024-02-04 20:17 UTC, Dweblenod approved these changes
This looks nice and clean, great work on the model and code! 

It looks like the outer layer of the model might cause z-fighting with the outer layer of the player skin but thats not an issue unique to this armor in our mod (also something that happens with our dreamer pajamas)

Will give @kirderf1 a chance to look over the code but I give it my approval. I do recognize that this needs crediting in CHANGELOG.md

2024-02-04 20:17 UTC, Dweblenod commented
Also should be getting merged into upcoming-content instead of 1.20.1

2024-02-05 19:08 UTC, kirderf1 requested changes
Yeah, changelog file changes is needed, and asset credits should be added to the PR description.
Geckolib documentation is suggesting that instances of `RawAnimation` should be cached in fields, like what I did in `ConsortEntity` for example. However while looking up things for writing it, I discovered `DefaultAnimations` which looks nice for situations like this.

2024-02-05 19:18 UTC, kirderf1 commented on src/main/java/com/mraof/minestuck/client/renderer/armor/PrismarineArmorRenderer.java
I don't think this class serves any meaningful purpose. I suggest that you use `GeoArmorRenderer` directly instead.

2024-02-07 04:03 UTC, KingBalDoro commented on src/main/java/com/mraof/minestuck/client/renderer/armor/PrismarineArmorRenderer.java
i don't know how to use that

2024-02-07 04:03 UTC, KingBalDoro commented on src/main/java/com/mraof/minestuck/item/armor/PrismarineArmorItem.java
> +	}
define "inline"

2024-02-09 16:27 UTC, kirderf1 commented on src/main/java/com/mraof/minestuck/item/armor/PrismarineArmorItem.java
> +		return PlayState.CONTINUE;
Looks like you missed some of the nuance of that function. The benefit of using `setAndContinue(...)` over `setAnimation(...)` is that the former also returns `PlayState.CONTINUE`. That's useful when you want to both set the animation and continue the animation like here, allowing you to `return state.setAndContinue(...);` (as opposed to setting the animation and returning separately).

2024-02-09 16:29 UTC, kirderf1 commented on src/main/java/com/mraof/minestuck/item/armor/PrismarineArmorItem.java
> +	}
https://www.jetbrains.com/help/idea/inline.html

2024-02-09 16:36 UTC, kirderf1 commented on src/main/java/com/mraof/minestuck/client/renderer/armor/PrismarineArmorRenderer.java
You might be able to inline `GeoArmorRenderer` directly. Otherwise, you can do it directly by replacing the `PrismarineArmorRenderer` field type with `GeoArmorRenderer<?>`, and the constructor with `new GeoArmorRenderer(new PrismarineArmorModel())`.

2024-02-10 13:11 UTC, kirderf1 approved these changes

2024-02-11 22:13 UTC, merged