1.20.1 patches
lunar-sway/minestuck pull request #631
Opened 2024-08-11 02:31 UTC by Dweblenod

Misc fixes

2024-08-11 02:34 UTC, Dweblenod commented on src/main/java/com/mraof/minestuck/data/tag/MinestuckBlockTagsProvider.java
> +		needsStoneAxe(UNCARVED_WOOD.get(), UNCARVED_WOOD_BUTTON.get(), UNCARVED_WOOD_FENCE.get(), UNCARVED_WOOD_FENCE_GATE.get(), UNCARVED_WOOD_PRESSURE_PLATE.get(), UNCARVED_WOOD_SLAB.get(),
The way it is now has no net effect in data files. I think it helps illustrate some peculiarities/inconsistencies with how the tags are handled for these blocks

2024-09-02 16:56 UTC, kirderf1 requested changes
Since this is targeting 1.20.1, how much of this is backports from the main branch, and how much also need to be fixed on the main branch?

2024-09-02 16:56 UTC, kirderf1 commented on CHANGELOG.md
> +- Removed default name visibility of Lotus Flower
I recall seeing this issue in 1.20.4, but was this also an issue back in 1.20.1?

2024-09-02 16:56 UTC, kirderf1 commented on CHANGELOG.md
> +- Changed bookshelf recipes to match their book drop rate
The recipes still need changing for this.

2024-09-06 00:21 UTC, Dweblenod commented
Regarding the two comments above on Minecraft version, everything present in this branch should be an issue in 1.20.4 although in messaging prior to this PR some of them have been stated as being 1.20.4 specific. I may have gotten versions mixed up or noticed the situation first when testing 1.20.4

2024-09-07 14:02 UTC, kirderf1 commented on CHANGELOG.md
> +- Added null check for target in MobAnimationPhaseGoal
Should be written to something more meaningful to the players.

2024-09-08 12:57 UTC, kirderf1 commented on CHANGELOG.md
> +- Removed default name visibility of Lotus Flower
Tested it out just now, and the 1.20.4 issue does not appear to be present in 1.20.1 with Minestuck only. Unless there's a specific reason to this for 1.20.1, I think that we should revert this and the `LotusFlowerEntity` change before merging this.

2024-09-08 15:55 UTC, kirderf1 approved these changes

2024-09-08 16:16 UTC, merged